Vgp233/xile chen/player movement
erickbordallo/WarSpecialists pull request #14
Opened 2020-08-25 14:29 UTC by ScottXileChen

Added first character "Maria".
Added PlayerBase and Maria class.
Added Maria animations.
Added MariaAC class to control Maria animations.
Baked NavMesh on GameMap scene.

2020-08-25 20:01 UTC, memogtt commented
I think you need to add a reviewer so Erick can receive the request

2020-08-25 21:16 UTC, erickbordallo requested changes
1) Remove that extra scenes. Just use Gameplay scene. The one that contains the current map.
2) Fix the conflicts. Merge master and check the conflicts that you are having. Fix them.

2020-08-25 21:16 UTC, erickbordallo commented on WarSpecialists/Assets/Scenes/GameplayMap_LOCAL_14768.meta
> +  assetBundleVariant:
Remove this Scene. Keep just GamePlay scene. The one with the final map.

2020-08-25 21:16 UTC, erickbordallo commented on WarSpecialists/Assets/Scenes/GameplayMap_LOCAL_14768.unity
>  Transform:
Same. Remove this extra scenes.

2020-08-26 01:14 UTC, ScottXileChen commented
Delete extra scene, and resolve conflict.

2020-08-26 01:16 UTC, erickbordallo approved these changes
Awesome. You can merge your changes.

2020-08-26 02:05 UTC, merged